name: Terraform Auto Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.1.7"
        cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}

    - name: terraform init
      run:
        terraform init

    - name: terraform format
      run:
        terraform fmt

    - name: terraform validate
      run:
        terraform validate

    - name: terraform apply
      run:
        terraform apply -auto-approve
